// Js and Css/react/react-fundamentals/src/components/PostItem.jsx
import React from 'react';
import MyButton from "./UI/button/MyButton";
import {useNavigate} from "react-router-dom";

const PostItem = (props) => {
    const router = useNavigate()

    return (
        <div className="post">
            <div className="post__content">
                <p><strong>{props.post.id} {props.post.title}</strong></p>
                <div>
                    {props.post.body}
                </div>
            </div>

            <div className="post__btns">
                <MyButton onClick={() => router(`${props.post.id}`)}>
                    Открыть
                </MyButton>
                <MyButton onClick={() => props.remove(props.post)}>
                    Удалить
                </MyButton>
            </div>
        </div>
    );
};

export default PostItem;

// Js and Css/vue/vueproject/src/components/PostItem.vue
<template>
    <div class="post">
        <div>
            <div>{{  post.id  }}</div>
            <div><strong>Название:</strong> {{ post.title }}</div> 
            <div><strong>Описание:</strong> {{ post.body }}</div>
        </div>
        <div class="post__btns">
            <my-button
                @click="$router.push(`/posts/${post.id}`)"
            >
                Посмотреть
            </my-button>

            <my-button
                @click="$emit('remove', post)"
            >
                Удалить
            </my-button>
        </div>
    </div>
</template>

<script>
// import MyButton from './UI/MyButton.vue'
// import MyButton from '@/components/UI/MyButton.vue'

export default {
    // components: {MyButton},
    props: {
        post: {
            type: Object,
            requried: true
        }
    }
}
</script>

<style>
.post {
    padding: 15px;
    border: 2px solid teal;
    margin-top: 15px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}

.post__btns {
    display: flex;
}
</style>
