// Js and Css/react/react-fund-course/src/components/PostForm.jsx
import React, {useState} from 'react';
import MyInput from "./UI/input/MyInput";
import MyButton from "./UI/button/MyButton";

const PostForm = ({create}) => {
    const [post, setPost] = useState({title: '', body: ''})

    const addNewPost = (e) => {
        e.preventDefault()
        const newPost = {
            ...post, id: Date.now()
        }
        create(newPost)
        setPost({title: '',body: ''})
    }

    return (
        <div>
            <form>
                {/* Управляемый компонент */}
                <MyInput
                    type="text"
                    value={post.title}
                    placeholder="Название поста"
                    onChange={e => setPost({...post, title: e.target.value})}
                />
                {/*Неуправляемый или неконтролируемый компонент*/}
                <MyInput
                    value={post.body}
                    onChange={e => setPost({...post, body: e.target.value})}
                    type="text"
                    placeholder="Описание поста"
                />
                <MyButton onClick={addNewPost}>Создать пост</MyButton>
            </form>
        </div>
    );
};

export default PostForm;

// Js and Css/vue/vueproject/src/components/PostForm.vue
<template>
    <form @submit.prevent>
        <h4>Создание поста</h4>

        <my-input
            v-model="post.title"
            type="text" 
            placeholder="Название"
        />
        <my-input 
            v-model="post.body"
            type="text" 
            placeholder="Описание"
        />
        <my-button 
            style="align-self:flex-end; margin-top: 15px;"
            @click="createPost"
        >
        Создать пост
        </my-button>
    </form>
</template>

<script>
// import MyButton from './UI/MyButton.vue'
// import MyButton from '@/components/UI/MyButton.vue'

export default {
    // components: {MyButton},
    data(){
        return {
            post: {
                title: '',
                body: ''
            }
        }
    },
    methods: {
        createPost(){
            this.post.id = Date.now()
            this.$emit('create', this.post)
            this.post = {
                title: '',
                body: ''
            }
        },
    }
}
</script>

<style scoped>
form {
    display: flex;
    flex-direction: column;
}
</style>
